### ISSUE TITLE
404s on Username Changes

### ISSUE THREAD

**Issue by sampoder** [hackclub/scrapbook#104]
It seems that when you change the username in Airtable, you then need to rebuild the whole site to remove the 404.

https://scrapbook.hackclub.com/sampoder/ is 404ing :(((

<img width="1183" alt="Screenshot 2020-10-02 at 10 48 56 PM" src="https://user-images.githubusercontent.com/39828164/94936895-76baec80-0501-11eb-989e-c7441f27b31e.png">

https://scrapbook.hackclub.com/sampoder/?welcome=false is not interestingly 

my theory is this is due to the pre-rendering, going to explore :D

**Comment by lachlanjc** [comment]
Yeah, something about prerendering. I wonder if fetching the page in advance with URL parameters would help with this?

**Comment by sampoder** [comment]
Facepalm

**Comment by sampoder** [comment]
sadly my fix did not fix this

**Comment by sampoder** [comment]
ahh so we made some progress: it now only 404s when you reset your profile to a username that would have been pre rendered. So for example changing my name from `sampoder` -> `sam` it works, but `sam` to `sampoder` doesn't

**Comment by lachlanjc** [comment]
If I’m understanding you correctly, that sounds fine. We pre-render the most active users’ profile pages, which obviously includes you, so if you changed your username back to something pre-rendered, it won’t re-render. If it’s working if you change your username to something randomly new, that’s perfect

**Comment by sampoder** [comment]
Yes, this is still on the tbale
