### ISSUE TITLE
scrapbook escapes escapes

### ISSUE THREAD

**Issue by sporeball** [hackclub/scrapbook#173]
i just noticed this behavior on a post of mine from a month ago:

![image](https://user-images.githubusercontent.com/12767408/115648900-2491bb00-a2db-11eb-8ef6-f4aa0f91290d.png)

the `<3` in the original post text is correctly normalized to `&lt;3`, but this is then wrongly further normalized to `&amp;lt;3`, which the browser does not parse as the original sequence anymore, leading to a broken caption.

**Comment by alhardwarehyde** [comment]
@sampoder also this one?

**Comment by sampoder** [comment]
Yes! Thanks Al!

**Comment by grymmy** [comment]
@JosiasAurel Please attempt to reproduce this and comment here, then assign back to me.

**Comment by JosiasAurel** [comment]
I do not experience this from scrapbook
