### ISSUE TITLE
Broken formatting on `/about` page

### ISSUE THREAD

**Issue by exu3** [hackclub/scrapbook#363]
<img width="813" alt="Screen Shot 2022-10-02 at 9 16 17 AM" src="https://user-images.githubusercontent.com/72365100/193456057-436bf9af-a264-40d5-974c-8e744d0f6a3c.png">

**Comment by Nevish-302** [comment]
can you assign this to me?

**Comment by sampoder** [comment]
Hey @Nevish-302, feel free to drop a PR with a fix!

**Comment by KunalSin9h** [comment]
@sampoder what do you think, why it's happening?

**Comment by IamTregsthedev** [comment]
what should it look like?

**Comment by sampoder** [comment]
Ideally, they'd be bullet points with links
