### ISSUE TITLE
Explore Community Discord Integration

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/scrapbook#450]
Blair Hack Club has their own bot that does this in Discord? Maybe Fork theirs?

**Comment by cytronicoder** [comment]
Discord? 👀

**Comment by cfanoulis** [comment]
this would need a bot that monitors either messages or reactions - which needs a websocket connection iirc

personal suggestion: @sapphiredev's Sapphire framework

**Comment by grymmy** [comment]
Closing this feature request as out of scope, please re-open the issue if you feel strongly and want to fight for its survival.
