### ISSUE TITLE
Scrapbook for clubs; issue with light mode

### ISSUE THREAD

**Issue by developedbytoby** [hackclub/scrapbook#473]
It's looking really good so far! However, on the form in the sign up modal, I'm running into this bug while using light mode:

![image](https://user-images.githubusercontent.com/77097223/223795837-8d31a7db-57d8-4455-82bf-a6db0ec0c667.png)

**Comment by sampoder** [comment]
Thanks for reporting @developedbytoby; this has now been fixed!

**Comment by developedbytoby** [comment]
Wahoo! Thanks Sam.
