### ISSUE TITLE
Emoji box won't go away

### ISSUE THREAD

**Issue by PellMellKid** [hackclub/scrapbook#474]
until you select an emoji. I clicked it to find out what "+" does, but I didn't actually want to leave an emoji.
![image](https://user-images.githubusercontent.com/109363156/223802211-066931d7-5c54-49c8-ad22-9253efac117e.png)

**Comment by sampoder** [comment]
This is design flaw - you can "exit" by clicking the empty space around the box. I'm going to add an X.

**Comment by sampoder** [comment]
Fixed!
