### ISSUE TITLE
Add the ability to change profile pic.

### ISSUE THREAD

**Issue by sonicx180** [hackclub/scrapbook#488]
When I login to scrapbook, I have my old google account's image. I would like to change this to my latest logo. Assigning this to my self

![image](https://user-images.githubusercontent.com/83236320/228385258-d9d7831e-84aa-4df6-a2ae-9113dcb65644.png)

**Comment by JosiasAurel** [comment]
@sonicx180 are you still planning to do this yourself? Or do you need a helping hand?

**Comment by sampoder** [comment]
fyi: this is pulling from Gravatar

**Comment by sonicx180** [comment]
i need help

**Comment by JosiasAurel** [comment]
btw @sonicx180 if you sign-in using Slack your profile picture should match the one you have on slack

**Comment by grymmy** [comment]
@JosiasAurel closing this issue as you merged #576 which seems to implement the requested feature...
