### ISSUE TITLE
Strikethrough doesn't work

### ISSUE THREAD

**Issue by jianmin-chen** [hackclub/scrapbook#489]
I haven't taken a look at what library is being used (i.e. this is probably just a small option addition), but strikethrough doesn't currently work. Small minor easy to solve problem.

**Comment by sampoder** [comment]
check out https://github.com/hackclub/scrapbook/blob/23285d2db5a40ea4634123e89ddc140f2be3a6ec/components/content.js#L52!

**Comment by grymmy** [comment]
This seems like a very reasonable feature request that might be easily delegatable - I leave you to find a home for this @JosiasAurel, or implement yourself if you feel so inclined...

**Comment by JosiasAurel** [comment]
implemented since #610
