### ISSUE TITLE
A dark mode option on the homepage

### ISSUE THREAD

**Issue by abhiraj-ku** [hackclub/scrapbook#496]
Having a dark mode is good for users who either don't like light mode or for users who have issue reading texts in light mode

**Comment by sampoder** [comment]
Dark mode has been implemented using [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).

**Comment by abhiraj-ku** [comment]
ok @sampoder . Can you suggest beginner issues to work on . Thanks in Advance
