### ISSUE TITLE
Streak increasing even without posting in Scrapbook 

### ISSUE THREAD

**Issue by SameerYasin** [hackclub/scrapbook#515]
I discovered a bug on an individual's page on scrapbook where his streak is continuously increasing without posting regularly or while posting in gaps of 2 days.
Later i discussed it with my friend shrey and we came to the conclusion to report it as a bug. 
![237423334-bf4c8423-368e-4f5f-80a9-0a37d78cf861](https://github.com/hackclub/scrapbook/assets/113780206/b96657fa-ff1b-43e8-ba7f-0cf8505c93a8)

**Comment by devramsean0** [comment]
Can reproduce that this is happening to me too

**Comment by grymmy** [comment]
@JosiasAurel I cannot fathom this is happening without being noticed presently - if you have any inkling as far as this still occurring, please re-open this issue and notify me...
