### ISSUE TITLE
Scrapbook/Scrappy listing incorrect/inconsistent streaks

### ISSUE THREAD

**Issue by BrightTheBackpack** [hackclub/scrapbook#626]
I just posted my scrapbook today, and it says i have a 5 day streak, even though yesterday I had a 2 day streak. This isn't a big deal, but maybe investigate. I suspect this has something to do with timezones or something.

**Comment by grymmy** [comment]
Josias,

Please investigate this when you have cycles.

**Comment by revaga** [comment]
![image](https://github.com/hackclub/scrapbook/assets/58123400/3962639b-7b66-40c5-b648-6e29ef30449f)
![image](https://github.com/hackclub/scrapbook/assets/58123400/374590ea-ec37-4346-96a6-fd09c9b191dd)
still happening?

**Comment by JosiasAurel** [comment]
think you for reporting @revaga will investigate

**Comment by JosiasAurel** [comment]
"This user always seems to be on top with a constant number of 45, is this a bug?" - a hackclubber

**Comment by ansh3108** [comment]
I'm that hackclubber lol

**Comment by JosiasAurel** [comment]
This issue is no longer occuring
