### ISSUE TITLE
2 different scrapbooks?!!

### ISSUE THREAD

**Issue by jakjakob** [hackclub/scrapbook#662]
idk what exactly the problem is, but I have a different scrapbook on my custom domain (scrapbook.jakjakob.eu) than the one of the hack club website - prob. doing setup something went wrong. The hack club one is the correctly linked one, the other one can also just be deleted - there is only one post I used to test it - Would be nice if someone could help me.

**Comment by JosiasAurel** [comment]
Hey @jakjakob do you have two different users on scrapbook?

**Comment by jakjakob** [comment]
https://scrapbook.hackclub.com/jakjakob that is the one I want to keep

https://scrapbook.jakjakob.eu that is the one I don't want to have/where I want to have the one stated above

**Comment by JosiasAurel** [comment]
did you make all those posts via slack?

**Comment by jakjakob** [comment]
the one I want to keep - yes

the other one via the website.

**Comment by JosiasAurel** [comment]
did you use a different email address from your slack email?

**Comment by jakjakob** [comment]
I always used the same, the post of the one I want to keep (only 1) I made it via slack

**Comment by JosiasAurel** [comment]
Hey. I removed the record of the unwanted account and put your custom domain on your main account.
