### ISSUE TITLE
bug: scrappy auto reactions aren't synced to the web ui

### ISSUE THREAD

**Issue by kcoderhtml** [hackclub/scrapbook#670]
This was tested with the `:ship:` emoji

**Comment by aramshiva** [comment]
I think this is on purpose, I believe scrappy wants to only log hack clubbers reactions but I may be wrong.

**Comment by kcoderhtml** [comment]
That would make sense; for the auto tagging features it's quite helpful though.

**Comment by kcoderhtml** [comment]
Thank you!
