### ISSUE TITLE
bug: my slack email doesn't sign me into my slack scrapbook acount

### ISSUE THREAD

**Issue by kcoderhtml** [hackclub/scrapbook#671]
I'm not sure how this happened, but I believe I first used scrapbook while there was an error which may have caused this.

**Comment by JosiasAurel** [comment]
what error had you encountered back then?

**Comment by kcoderhtml** [comment]
I don't remember; i just have a vague recollection of there being downtime around the time i first used it

**Comment by kcoderhtml** [comment]
Sorry for not having more info; no one else seems to have this issue, so I am more asking whether my broken account with the email: gawpw06r@duck.com could be removed and my working scrapbook account: https://scrapbook.hackclub.com/Kieran could have that email connected to it. I'm guessing that part of the issue might be that emails aren't updated when a user changes their email in the slack workspace. Sorry for not being clear before :)

**Comment by JosiasAurel** [comment]
closing as done!
