### ISSUE TITLE
Account errors

### ISSUE THREAD

**Issue by nguyengiabach1201** [hackclub/scrapbook#776]
I have some problems with my account:
- The first thing is I can't log-in to my account, the web just simply doesn't send me any email :(
- And there the huge problem comes: I magically 2 account for Scrapbook

[The new one](https://scrapbook.hackclub.com/Nguy%E1%BB%85nGiaB%C3%A1ch)
![image](https://github.com/hackclub/scrapbook/assets/108968549/05f62fb4-701a-4a17-97c2-8ea7dfc942d0)

[The old one](https://scrapbook.hackclub.com/nguyengiabach1201)
![image](https://github.com/hackclub/scrapbook/assets/108968549/c2fd7845-c40c-490d-b6ec-ead6a85bbc90)

So, I think because it has 2 accounts link to 1 email so Scrapbook doesn't send me my log-in email.

**Comment by JosiasAurel** [comment]
@nguyengiabach1201 you should now be able to log into your scrapbook account. As for the second issue, pls DM me the link to both of those account and the email used and I can probably help you with that.
