### ISSUE TITLE
Deleting a post too fast creates a ghost post in your scrapbook

### ISSUE THREAD

**Issue by Suyashtnt** [hackclub/scrapbook#785]
I created a post for Hackclub arcade, which I then had to delete for an unrelated reason soon after. However, scrappy didn't delete the post itself on scrapbook (it didn't send any confirmed deletion message as well) so it's on my page without it being inside of the scrapbook channel on the slack.

My scrapbook: https://scrapbook.hackclub.com/ABadlyDrawnWobbler
the post in question: Jun 29@ 2:29PM (`cly04y7ng001jbk0st68mj2g7`)

**Comment by JosiasAurel** [comment]
could reproduce!

**Comment by JosiasAurel** [comment]
So it appears that when you delete the post too quick scrappy does not get the delete event!
