### ISSUE TITLE
Creation of new account on login, despite existence of previous account

### ISSUE THREAD

**Issue by not-first** [hackclub/scrapbook#799]
I tried to log in to scrapbook using my email the same as slack, and it made a new account, seperate from my one from slack
My current scrapbook username is 'Ollie', and when I logged in it made 'ollie'. Maybe because I did a slack username change after my first scrapbook post?

I would like to delete the lowercase 'ollie' account which has no posts, and change my username to the lowercase version. From 'Ollie' to 'ollie'.

**Comment by JosiasAurel** [comment]
#797
