### ISSUE TITLE
CSS Linking is broken.

### ISSUE THREAD

**Issue by NimitVijayvargee** [hackclub/scrapbook#811]
CSS Linking does not function as intended. Code is successfully linked to profile but does not appear on the actual site. Previews of the CSS are unaffected.
My scrapbook page:
![My scrapbook page](https://github.com/user-attachments/assets/68617e32-aac0-49a1-b7c8-0fe3e0ea1a04)
Scrapbook Customizer preview:
![image](https://github.com/user-attachments/assets/82c3f6d2-d934-40d5-8b06-f0fadd71aa11)
Github Gist Link:
"https://gist.githubusercontent.com/NimitVijayvargee/e6052e6ea68eca8ed6c319c107313e5a/raw/fab771983368f067bd89df93617318d498eb9a01/style.css"

Also note that the undocumented API (scrapbook.hackclub.com/api/users/...) displays accurate CSS.
![image](https://github.com/user-attachments/assets/9f87509b-628e-42dc-910c-92ffa1d80a7c)

**Comment by JosiasAurel** [comment]
After some digging, it appears simply linking a css file from a source without including the proper MIME type (`text/css` in this case) would result in the styles not being applied. 

The linked PR fixes this issue!
